export const ADD_CONTACT = 'ADD_CONTACT'

export const UPDATE_CONTACT = 'UPDATE_CONTACT'

export const DELETE_CONTACT = 'DELETE_CONTACT'

export const CHANGE_STATE_FAVORITE = 'CHANGE_STATE_FAVORITE'

export const SORT_CONTACTS_BY_FAVORITES = 'SORT_CONTACTS_BY_FAVORITES'

export const LIST_ALL_CONTACTS = 'LIST_ALL_CONTACTS'

export const CHANGE_STATE_IS_OPEN_SIDEBAR = 'CHANGE_STATE_IS_OPEN_SIDEBAR'