export const ADD_CONTACT = 'ADD_CONTACT'

export const UPDATE_CONTACT = 'UPDATE_CONTACT'

export const SET_VIEWABLE_CONTACT = 'SET_VIEWABLE_CONTACT'

export const UPDATE_LIST_GROUPS = 'UPDATE_LIST_GROUPS'