export const ADD_CONTACT = 'ADD_CONTACT'

export const UPDATE_CONTACT = 'UPDATE_CONTACT'

export const GET_CONTACT = 'GET_CONTACT'

export const DELETE_CONTACT = 'DELETE_CONTACT'

export const CHANGE_STATE_FAVORITE = 'CHANGE_STATE_FAVORITE'

export const SORT_CONTACTS_BY_FAVORITES = 'SORT_CONTACTS_BY_FAVORITES'

export const LIST_ALL_CONTACTS = 'LIST_ALL_CONTACTS'

export const CHANGE_STATE_IS_OPEN_SIDEBAR = 'CHANGE_STATE_IS_OPEN_SIDEBAR'

export const SET_VIEWABLE_CONTACT = 'SET_VIEWABLE_CONTACT'

export const HIDE_WINDOW_CONTACT_VIEWING = 'HIDE_WINDOW_CONTACT_VIEWING'